export const TEAM_FLAGS = {
  "Arsenal": "Ã°Å¸â€Â´", "Atlético de Madrid": "Ã°Å¸â€Â´Ã°Å¸â€Âµ", "Bayern Munich": "Ã°Å¸â€Â´Ã¢Å¡Âª", "PSG": "Ã°Å¸â€ÂµÃ°Å¸â€Â´",
  "MÃƒÆ’Ã‚Â©xico": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â²ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â½", "Corea del Sur": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â°ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â·", "SudÃƒÆ’Ã‚Â¡frica": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¿ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¦", "RepÃƒÆ’Ã‚Âºblica Checa": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¨ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¿",
  "CanadÃƒÆ’Ã‚Â¡": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¨ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¦", "Suiza": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¨ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â­", "Qatar": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¶ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¦", "Bosnia y Herzegovina": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â§ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¦",
  "Brasil": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â§ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â·", "Marruecos": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â²ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¦", "Escocia": "ÃƒÂ°Ã…Â¸Ã‚ÂÃ‚Â´", "HaitÃƒÆ’Ã‚Â­": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â­ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¹",
  "Estados Unidos": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚ÂºÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¸", "Australia": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¦ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Âº", "Paraguay": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚ÂµÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¾", "TurquÃƒÆ’Ã‚Â­a": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¹ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â·",
  "Alemania": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â©ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Âª", "Ecuador": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚ÂªÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¨", "Costa de Marfil": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¨ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â®", "Curazao": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¨ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¼",
  "PaÃƒÆ’Ã‚Â­ses Bajos": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â³ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â±", "JapÃƒÆ’Ã‚Â³n": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¯ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Âµ", "TÃƒÆ’Ã‚Âºnez": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¹ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â³", "Suecia": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¸ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Âª",
  "BÃƒÆ’Ã‚Â©lgica": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â§ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Âª", "IrÃƒÆ’Ã‚Â¡n": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â®ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â·", "Egipto": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚ÂªÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¬", "Nueva Zelandia": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â³ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¿",
  "EspaÃƒÆ’Ã‚Â±a": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚ÂªÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¸", "Uruguay": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚ÂºÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¾", "Cabo Verde": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¨ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â»", "Arabia Saudita": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¸ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¦",
  "Francia": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â«ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â·", "Senegal": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¸ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â³", "Noruega": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â³ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â´", "Iraq": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â®ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¶",
  "Argentina": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¦ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â·", "Argelia": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â©ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¿", "Austria": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¦ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¹", "Jordania": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¯ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â´",
  "Portugal": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚ÂµÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¹", "Colombia": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¨ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â´", "UzbekistÃƒÆ’Ã‚Â¡n": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚ÂºÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¿", "RD del Congo": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¨ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â©",
  "Inglaterra": "ÃƒÂ°Ã…Â¸Ã‚ÂÃ‚Â´", "Croacia": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â­ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â·", "PanamÃƒÆ’Ã‚Â¡": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚ÂµÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¦", "Ghana": "ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â¬ÃƒÂ°Ã…Â¸Ã¢â‚¬Â¡Ã‚Â­"
};

export const WC2026_MATCHES = [
  {"id": "m001", "homeTeam": "MÃƒÆ’Ã‚Â©xico", "awayTeam": "SudÃƒÆ’Ã‚Â¡frica", "datetime": "2026-06-11T19:00:00Z", "phase": "groups", "group": "A", "stadium": "Ciudad de MÃƒÆ’Ã‚Â©xico", "enabled": false},
  {"id": "m002", "homeTeam": "Corea del Sur", "awayTeam": "RepÃƒÆ’Ã‚Âºblica Checa", "datetime": "2026-06-12T02:00:00Z", "phase": "groups", "group": "A", "stadium": "Guadalajara", "enabled": false},
  {"id": "m003", "homeTeam": "RepÃƒÆ’Ã‚Âºblica Checa", "awayTeam": "SudÃƒÆ’Ã‚Â¡frica", "datetime": "2026-06-18T16:00:00Z", "phase": "groups", "group": "A", "stadium": "Atlanta", "enabled": false},
  {"id": "m004", "homeTeam": "MÃƒÆ’Ã‚Â©xico", "awayTeam": "Corea del Sur", "datetime": "2026-06-19T01:00:00Z", "phase": "groups", "group": "A", "stadium": "Guadalajara", "enabled": false},
  {"id": "m005", "homeTeam": "RepÃƒÆ’Ã‚Âºblica Checa", "awayTeam": "MÃƒÆ’Ã‚Â©xico", "datetime": "2026-06-25T02:00:00Z", "phase": "groups", "group": "A", "stadium": "Ciudad de MÃƒÆ’Ã‚Â©xico", "enabled": false},
  {"id": "m006", "homeTeam": "SudÃƒÆ’Ã‚Â¡frica", "awayTeam": "Corea del Sur", "datetime": "2026-06-25T02:00:00Z", "phase": "groups", "group": "A", "stadium": "Monterrey", "enabled": false},
  {"id": "m007", "homeTeam": "CanadÃƒÆ’Ã‚Â¡", "awayTeam": "Bosnia y Herzegovina", "datetime": "2026-06-12T20:00:00Z", "phase": "groups", "group": "B", "stadium": "Toronto", "enabled": false},
  {"id": "m008", "homeTeam": "Qatar", "awayTeam": "Suiza", "datetime": "2026-06-13T13:00:00Z", "phase": "groups", "group": "B", "stadium": "San Francisco", "enabled": false},
  {"id": "m009", "homeTeam": "Suiza", "awayTeam": "Bosnia y Herzegovina", "datetime": "2026-06-18T11:00:00Z", "phase": "groups", "group": "B", "stadium": "Los ÃƒÆ’Ã‚Ângeles", "enabled": false},
  {"id": "m010", "homeTeam": "CanadÃƒÆ’Ã‚Â¡", "awayTeam": "Qatar", "datetime": "2026-06-18T22:00:00Z", "phase": "groups", "group": "B", "stadium": "Vancouver", "enabled": false},
  {"id": "m011", "homeTeam": "Suiza", "awayTeam": "CanadÃƒÆ’Ã‚Â¡", "datetime": "2026-06-24T19:00:00Z", "phase": "groups", "group": "B", "stadium": "Vancouver", "enabled": false},
  {"id": "m012", "homeTeam": "Bosnia y Herzegovina", "awayTeam": "Qatar", "datetime": "2026-06-24T19:00:00Z", "phase": "groups", "group": "B", "stadium": "Seattle", "enabled": false},
  {"id": "m013", "homeTeam": "Brasil", "awayTeam": "Marruecos", "datetime": "2026-06-14T00:00:00Z", "phase": "groups", "group": "C", "stadium": "Nueva York/NJ", "enabled": false},
  {"id": "m014", "homeTeam": "HaitÃƒÆ’Ã‚Â­", "awayTeam": "Escocia", "datetime": "2026-06-13T22:00:00Z", "phase": "groups", "group": "C", "stadium": "Boston", "enabled": false},
  {"id": "m015", "homeTeam": "Escocia", "awayTeam": "Marruecos", "datetime": "2026-06-19T22:00:00Z", "phase": "groups", "group": "C", "stadium": "Boston", "enabled": false},
  {"id": "m016", "homeTeam": "Brasil", "awayTeam": "HaitÃƒÆ’Ã‚Â­", "datetime": "2026-06-20T00:00:00Z", "phase": "groups", "group": "C", "stadium": "Filadelfia", "enabled": false},
  {"id": "m017", "homeTeam": "Escocia", "awayTeam": "Brasil", "datetime": "2026-06-24T22:00:00Z", "phase": "groups", "group": "C", "stadium": "Miami", "enabled": false},
  {"id": "m018", "homeTeam": "Marruecos", "awayTeam": "HaitÃƒÆ’Ã‚Â­", "datetime": "2026-06-24T22:00:00Z", "phase": "groups", "group": "C", "stadium": "Atlanta", "enabled": false},
  {"id": "m019", "homeTeam": "Estados Unidos", "awayTeam": "Paraguay", "datetime": "2026-06-12T18:00:00Z", "phase": "groups", "group": "D", "stadium": "Los ÃƒÆ’Ã‚Ângeles", "enabled": false},
  {"id": "m020", "homeTeam": "Australia", "awayTeam": "TurquÃƒÆ’Ã‚Â­a", "datetime": "2026-06-13T01:00:00Z", "phase": "groups", "group": "D", "stadium": "Vancouver", "enabled": false},
  {"id": "m021", "homeTeam": "TurquÃƒÆ’Ã‚Â­a", "awayTeam": "Paraguay", "datetime": "2026-06-18T19:00:00Z", "phase": "groups", "group": "D", "stadium": "San Francisco", "enabled": false},
  {"id": "m022", "homeTeam": "Estados Unidos", "awayTeam": "Australia", "datetime": "2026-06-19T19:00:00Z", "phase": "groups", "group": "D", "stadium": "Seattle", "enabled": false},
  {"id": "m023", "homeTeam": "TurquÃƒÆ’Ã‚Â­a", "awayTeam": "Estados Unidos", "datetime": "2026-06-26T03:00:00Z", "phase": "groups", "group": "D", "stadium": "Los ÃƒÆ’Ã‚Ângeles", "enabled": false},
  {"id": "m024", "homeTeam": "Paraguay", "awayTeam": "Australia", "datetime": "2026-06-26T03:00:00Z", "phase": "groups", "group": "D", "stadium": "San Francisco", "enabled": false},
  {"id": "m025", "homeTeam": "Alemania", "awayTeam": "Curazao", "datetime": "2026-06-14T18:00:00Z", "phase": "groups", "group": "E", "stadium": "Houston", "enabled": false},
  {"id": "m026", "homeTeam": "Costa de Marfil", "awayTeam": "Ecuador", "datetime": "2026-06-15T00:00:00Z", "phase": "groups", "group": "E", "stadium": "Filadelfia", "enabled": false},
  {"id": "m027", "homeTeam": "Alemania", "awayTeam": "Costa de Marfil", "datetime": "2026-06-20T20:00:00Z", "phase": "groups", "group": "E", "stadium": "Toronto", "enabled": false},
  {"id": "m028", "homeTeam": "Ecuador", "awayTeam": "Curazao", "datetime": "2026-06-21T00:00:00Z", "phase": "groups", "group": "E", "stadium": "Kansas City", "enabled": false},
  {"id": "m029", "homeTeam": "Ecuador", "awayTeam": "Alemania", "datetime": "2026-06-25T20:00:00Z", "phase": "groups", "group": "E", "stadium": "Nueva York/NJ", "enabled": false},
  {"id": "m030", "homeTeam": "Curazao", "awayTeam": "Costa de Marfil", "datetime": "2026-06-25T20:00:00Z", "phase": "groups", "group": "E", "stadium": "Filadelfia", "enabled": false},
  {"id": "m031", "homeTeam": "PaÃƒÆ’Ã‚Â­ses Bajos", "awayTeam": "JapÃƒÆ’Ã‚Â³n", "datetime": "2026-06-14T19:00:00Z", "phase": "groups", "group": "F", "stadium": "Dallas", "enabled": false},
  {"id": "m032", "homeTeam": "Suecia", "awayTeam": "TÃƒÆ’Ã‚Âºnez", "datetime": "2026-06-15T03:00:00Z", "phase": "groups", "group": "F", "stadium": "Monterrey", "enabled": false},
  {"id": "m033", "homeTeam": "PaÃƒÆ’Ã‚Â­ses Bajos", "awayTeam": "Suecia", "datetime": "2026-06-20T17:00:00Z", "phase": "groups", "group": "F", "stadium": "Houston", "enabled": false},
  {"id": "m034", "homeTeam": "TÃƒÆ’Ã‚Âºnez", "awayTeam": "JapÃƒÆ’Ã‚Â³n", "datetime": "2026-06-20T04:00:00Z", "phase": "groups", "group": "F", "stadium": "Monterrey", "enabled": false},
  {"id": "m035", "homeTeam": "JapÃƒÆ’Ã‚Â³n", "awayTeam": "Suecia", "datetime": "2026-06-26T01:00:00Z", "phase": "groups", "group": "F", "stadium": "Dallas", "enabled": false},
  {"id": "m036", "homeTeam": "TÃƒÆ’Ã‚Âºnez", "awayTeam": "PaÃƒÆ’Ã‚Â­ses Bajos", "datetime": "2026-06-26T01:00:00Z", "phase": "groups", "group": "F", "stadium": "Kansas City", "enabled": false},
  {"id": "m037", "homeTeam": "IrÃƒÆ’Ã‚Â¡n", "awayTeam": "Nueva Zelandia", "datetime": "2026-06-16T04:00:00Z", "phase": "groups", "group": "G", "stadium": "Los ÃƒÆ’Ã‚Ângeles", "enabled": false},
  {"id": "m038", "homeTeam": "BÃƒÆ’Ã‚Â©lgica", "awayTeam": "Egipto", "datetime": "2026-06-15T20:00:00Z", "phase": "groups", "group": "G", "stadium": "Seattle", "enabled": false},
  {"id": "m039", "homeTeam": "BÃƒÆ’Ã‚Â©lgica", "awayTeam": "IrÃƒÆ’Ã‚Â¡n", "datetime": "2026-06-21T20:00:00Z", "phase": "groups", "group": "G", "stadium": "Los ÃƒÆ’Ã‚Ângeles", "enabled": false},
  {"id": "m040", "homeTeam": "Nueva Zelandia", "awayTeam": "Egipto", "datetime": "2026-06-22T02:00:00Z", "phase": "groups", "group": "G", "stadium": "Vancouver", "enabled": false},
  {"id": "m041", "homeTeam": "Egipto", "awayTeam": "IrÃƒÆ’Ã‚Â¡n", "datetime": "2026-06-27T02:00:00Z", "phase": "groups", "group": "G", "stadium": "Seattle", "enabled": false},
  {"id": "m042", "homeTeam": "Nueva Zelandia", "awayTeam": "BÃƒÆ’Ã‚Â©lgica", "datetime": "2026-06-27T02:00:00Z", "phase": "groups", "group": "G", "stadium": "Vancouver", "enabled": false},
  {"id": "m043", "homeTeam": "EspaÃƒÆ’Ã‚Â±a", "awayTeam": "Cabo Verde", "datetime": "2026-06-15T18:00:00Z", "phase": "groups", "group": "H", "stadium": "Atlanta", "enabled": false},
  {"id": "m044", "homeTeam": "Arabia Saudita", "awayTeam": "Uruguay", "datetime": "2026-06-16T00:00:00Z", "phase": "groups", "group": "H", "stadium": "Miami", "enabled": false},
  {"id": "m045", "homeTeam": "EspaÃƒÆ’Ã‚Â±a", "awayTeam": "Arabia Saudita", "datetime": "2026-06-21T18:00:00Z", "phase": "groups", "group": "H", "stadium": "Atlanta", "enabled": false},
  {"id": "m046", "homeTeam": "Uruguay", "awayTeam": "Cabo Verde", "datetime": "2026-06-22T00:00:00Z", "phase": "groups", "group": "H", "stadium": "Miami", "enabled": false},
  {"id": "m047", "homeTeam": "Cabo Verde", "awayTeam": "Arabia Saudita", "datetime": "2026-06-26T19:00:00Z", "phase": "groups", "group": "H", "stadium": "Houston", "enabled": false},
  {"id": "m048", "homeTeam": "Uruguay", "awayTeam": "EspaÃƒÆ’Ã‚Â±a", "datetime": "2026-06-27T02:00:00Z", "phase": "groups", "group": "H", "stadium": "Guadalajara", "enabled": false},
  {"id": "m049", "homeTeam": "Francia", "awayTeam": "Senegal", "datetime": "2026-06-16T20:00:00Z", "phase": "groups", "group": "I", "stadium": "Nueva York/NJ", "enabled": false},
  {"id": "m050", "homeTeam": "Iraq", "awayTeam": "Noruega", "datetime": "2026-06-16T22:00:00Z", "phase": "groups", "group": "I", "stadium": "Boston", "enabled": false},
  {"id": "m051", "homeTeam": "Francia", "awayTeam": "Iraq", "datetime": "2026-06-22T22:00:00Z", "phase": "groups", "group": "I", "stadium": "Filadelfia", "enabled": false},
  {"id": "m052", "homeTeam": "Noruega", "awayTeam": "Senegal", "datetime": "2026-06-23T00:00:00Z", "phase": "groups", "group": "I", "stadium": "Nueva York/NJ", "enabled": false},
  {"id": "m053", "homeTeam": "Noruega", "awayTeam": "Francia", "datetime": "2026-06-26T18:00:00Z", "phase": "groups", "group": "I", "stadium": "Boston", "enabled": false},
  {"id": "m054", "homeTeam": "Senegal", "awayTeam": "Iraq", "datetime": "2026-06-26T18:00:00Z", "phase": "groups", "group": "I", "stadium": "Toronto", "enabled": false},
  {"id": "m055", "homeTeam": "Argentina", "awayTeam": "Argelia", "datetime": "2026-06-17T02:00:00Z", "phase": "groups", "group": "J", "stadium": "Kansas City", "enabled": false},
  {"id": "m056", "homeTeam": "Austria", "awayTeam": "Jordania", "datetime": "2026-06-17T04:00:00Z", "phase": "groups", "group": "J", "stadium": "San Francisco", "enabled": false},
  {"id": "m057", "homeTeam": "Argentina", "awayTeam": "Austria", "datetime": "2026-06-22T18:00:00Z", "phase": "groups", "group": "J", "stadium": "Dallas", "enabled": false},
  {"id": "m058", "homeTeam": "Jordania", "awayTeam": "Argelia", "datetime": "2026-06-23T04:00:00Z", "phase": "groups", "group": "J", "stadium": "San Francisco", "enabled": false},
  {"id": "m059", "homeTeam": "Argelia", "awayTeam": "Austria", "datetime": "2026-06-28T02:00:00Z", "phase": "groups", "group": "J", "stadium": "Kansas City", "enabled": false},
  {"id": "m060", "homeTeam": "Jordania", "awayTeam": "Argentina", "datetime": "2026-06-28T02:00:00Z", "phase": "groups", "group": "J", "stadium": "Dallas", "enabled": false},
  {"id": "m061", "homeTeam": "Portugal", "awayTeam": "RD del Congo", "datetime": "2026-06-17T17:00:00Z", "phase": "groups", "group": "K", "stadium": "Houston", "enabled": false},
  {"id": "m062", "homeTeam": "UzbekistÃƒÆ’Ã‚Â¡n", "awayTeam": "Colombia", "datetime": "2026-06-18T02:00:00Z", "phase": "groups", "group": "K", "stadium": "Ciudad de MÃƒÆ’Ã‚Â©xico", "enabled": false},
  {"id": "m063", "homeTeam": "Portugal", "awayTeam": "UzbekistÃƒÆ’Ã‚Â¡n", "datetime": "2026-06-23T17:00:00Z", "phase": "groups", "group": "K", "stadium": "Houston", "enabled": false},
  {"id": "m064", "homeTeam": "RD del Congo", "awayTeam": "Colombia", "datetime": "2026-06-24T02:00:00Z", "phase": "groups", "group": "K", "stadium": "Guadalajara", "enabled": false},
  {"id": "m065", "homeTeam": "Colombia", "awayTeam": "Portugal", "datetime": "2026-06-27T23:30:00Z", "phase": "groups", "group": "K", "stadium": "Miami", "enabled": false},
  {"id": "m066", "homeTeam": "RD del Congo", "awayTeam": "UzbekistÃƒÆ’Ã‚Â¡n", "datetime": "2026-06-27T23:30:00Z", "phase": "groups", "group": "K", "stadium": "Atlanta", "enabled": false},
  {"id": "m067", "homeTeam": "Inglaterra", "awayTeam": "Croacia", "datetime": "2026-06-17T19:00:00Z", "phase": "groups", "group": "L", "stadium": "Dallas", "enabled": false},
  {"id": "m068", "homeTeam": "Ghana", "awayTeam": "PanamÃƒÆ’Ã‚Â¡", "datetime": "2026-06-17T23:00:00Z", "phase": "groups", "group": "L", "stadium": "Toronto", "enabled": false},
  {"id": "m069", "homeTeam": "Inglaterra", "awayTeam": "Ghana", "datetime": "2026-06-23T19:00:00Z", "phase": "groups", "group": "L", "stadium": "Boston", "enabled": false},
  {"id": "m070", "homeTeam": "PanamÃƒÆ’Ã‚Â¡", "awayTeam": "Croacia", "datetime": "2026-06-23T23:00:00Z", "phase": "groups", "group": "L", "stadium": "Toronto", "enabled": false},
  {"id": "m071", "homeTeam": "PanamÃƒÆ’Ã‚Â¡", "awayTeam": "Inglaterra", "datetime": "2026-06-27T21:00:00Z", "phase": "groups", "group": "L", "stadium": "Nueva York/NJ", "enabled": false},
  {"id": "m072", "homeTeam": "Croacia", "awayTeam": "Ghana", "datetime": "2026-06-27T21:00:00Z", "phase": "groups", "group": "L", "stadium": "Filadelfia", "enabled": false},
];

