export const TEAM_FLAGS = {
  "Arsenal": "🔴", "Atletico Madrid": "🔴🔵", "Bayern Munich": "🔴⚪", "PSG": "🔵🔴",
  "MÃ©xico": "ðŸ‡²ðŸ‡½", "Corea del Sur": "ðŸ‡°ðŸ‡·", "SudÃ¡frica": "ðŸ‡¿ðŸ‡¦", "RepÃºblica Checa": "ðŸ‡¨ðŸ‡¿",
  "CanadÃ¡": "ðŸ‡¨ðŸ‡¦", "Suiza": "ðŸ‡¨ðŸ‡­", "Qatar": "ðŸ‡¶ðŸ‡¦", "Bosnia y Herzegovina": "ðŸ‡§ðŸ‡¦",
  "Brasil": "ðŸ‡§ðŸ‡·", "Marruecos": "ðŸ‡²ðŸ‡¦", "Escocia": "ðŸ´", "HaitÃ­": "ðŸ‡­ðŸ‡¹",
  "Estados Unidos": "ðŸ‡ºðŸ‡¸", "Australia": "ðŸ‡¦ðŸ‡º", "Paraguay": "ðŸ‡µðŸ‡¾", "TurquÃ­a": "ðŸ‡¹ðŸ‡·",
  "Alemania": "ðŸ‡©ðŸ‡ª", "Ecuador": "ðŸ‡ªðŸ‡¨", "Costa de Marfil": "ðŸ‡¨ðŸ‡®", "Curazao": "ðŸ‡¨ðŸ‡¼",
  "PaÃ­ses Bajos": "ðŸ‡³ðŸ‡±", "JapÃ³n": "ðŸ‡¯ðŸ‡µ", "TÃºnez": "ðŸ‡¹ðŸ‡³", "Suecia": "ðŸ‡¸ðŸ‡ª",
  "BÃ©lgica": "ðŸ‡§ðŸ‡ª", "IrÃ¡n": "ðŸ‡®ðŸ‡·", "Egipto": "ðŸ‡ªðŸ‡¬", "Nueva Zelandia": "ðŸ‡³ðŸ‡¿",
  "EspaÃ±a": "ðŸ‡ªðŸ‡¸", "Uruguay": "ðŸ‡ºðŸ‡¾", "Cabo Verde": "ðŸ‡¨ðŸ‡»", "Arabia Saudita": "ðŸ‡¸ðŸ‡¦",
  "Francia": "ðŸ‡«ðŸ‡·", "Senegal": "ðŸ‡¸ðŸ‡³", "Noruega": "ðŸ‡³ðŸ‡´", "Iraq": "ðŸ‡®ðŸ‡¶",
  "Argentina": "ðŸ‡¦ðŸ‡·", "Argelia": "ðŸ‡©ðŸ‡¿", "Austria": "ðŸ‡¦ðŸ‡¹", "Jordania": "ðŸ‡¯ðŸ‡´",
  "Portugal": "ðŸ‡µðŸ‡¹", "Colombia": "ðŸ‡¨ðŸ‡´", "UzbekistÃ¡n": "ðŸ‡ºðŸ‡¿", "RD del Congo": "ðŸ‡¨ðŸ‡©",
  "Inglaterra": "ðŸ´", "Croacia": "ðŸ‡­ðŸ‡·", "PanamÃ¡": "ðŸ‡µðŸ‡¦", "Ghana": "ðŸ‡¬ðŸ‡­"
};

export const WC2026_MATCHES = [
  {"id": "m001", "homeTeam": "MÃ©xico", "awayTeam": "SudÃ¡frica", "datetime": "2026-06-11T19:00:00Z", "phase": "groups", "group": "A", "stadium": "Ciudad de MÃ©xico", "enabled": false},
  {"id": "m002", "homeTeam": "Corea del Sur", "awayTeam": "RepÃºblica Checa", "datetime": "2026-06-12T02:00:00Z", "phase": "groups", "group": "A", "stadium": "Guadalajara", "enabled": false},
  {"id": "m003", "homeTeam": "RepÃºblica Checa", "awayTeam": "SudÃ¡frica", "datetime": "2026-06-18T16:00:00Z", "phase": "groups", "group": "A", "stadium": "Atlanta", "enabled": false},
  {"id": "m004", "homeTeam": "MÃ©xico", "awayTeam": "Corea del Sur", "datetime": "2026-06-19T01:00:00Z", "phase": "groups", "group": "A", "stadium": "Guadalajara", "enabled": false},
  {"id": "m005", "homeTeam": "RepÃºblica Checa", "awayTeam": "MÃ©xico", "datetime": "2026-06-25T02:00:00Z", "phase": "groups", "group": "A", "stadium": "Ciudad de MÃ©xico", "enabled": false},
  {"id": "m006", "homeTeam": "SudÃ¡frica", "awayTeam": "Corea del Sur", "datetime": "2026-06-25T02:00:00Z", "phase": "groups", "group": "A", "stadium": "Monterrey", "enabled": false},
  {"id": "m007", "homeTeam": "CanadÃ¡", "awayTeam": "Bosnia y Herzegovina", "datetime": "2026-06-12T20:00:00Z", "phase": "groups", "group": "B", "stadium": "Toronto", "enabled": false},
  {"id": "m008", "homeTeam": "Qatar", "awayTeam": "Suiza", "datetime": "2026-06-13T13:00:00Z", "phase": "groups", "group": "B", "stadium": "San Francisco", "enabled": false},
  {"id": "m009", "homeTeam": "Suiza", "awayTeam": "Bosnia y Herzegovina", "datetime": "2026-06-18T11:00:00Z", "phase": "groups", "group": "B", "stadium": "Los Ãngeles", "enabled": false},
  {"id": "m010", "homeTeam": "CanadÃ¡", "awayTeam": "Qatar", "datetime": "2026-06-18T22:00:00Z", "phase": "groups", "group": "B", "stadium": "Vancouver", "enabled": false},
  {"id": "m011", "homeTeam": "Suiza", "awayTeam": "CanadÃ¡", "datetime": "2026-06-24T19:00:00Z", "phase": "groups", "group": "B", "stadium": "Vancouver", "enabled": false},
  {"id": "m012", "homeTeam": "Bosnia y Herzegovina", "awayTeam": "Qatar", "datetime": "2026-06-24T19:00:00Z", "phase": "groups", "group": "B", "stadium": "Seattle", "enabled": false},
  {"id": "m013", "homeTeam": "Brasil", "awayTeam": "Marruecos", "datetime": "2026-06-14T00:00:00Z", "phase": "groups", "group": "C", "stadium": "Nueva York/NJ", "enabled": false},
  {"id": "m014", "homeTeam": "HaitÃ­", "awayTeam": "Escocia", "datetime": "2026-06-13T22:00:00Z", "phase": "groups", "group": "C", "stadium": "Boston", "enabled": false},
  {"id": "m015", "homeTeam": "Escocia", "awayTeam": "Marruecos", "datetime": "2026-06-19T22:00:00Z", "phase": "groups", "group": "C", "stadium": "Boston", "enabled": false},
  {"id": "m016", "homeTeam": "Brasil", "awayTeam": "HaitÃ­", "datetime": "2026-06-20T00:00:00Z", "phase": "groups", "group": "C", "stadium": "Filadelfia", "enabled": false},
  {"id": "m017", "homeTeam": "Escocia", "awayTeam": "Brasil", "datetime": "2026-06-24T22:00:00Z", "phase": "groups", "group": "C", "stadium": "Miami", "enabled": false},
  {"id": "m018", "homeTeam": "Marruecos", "awayTeam": "HaitÃ­", "datetime": "2026-06-24T22:00:00Z", "phase": "groups", "group": "C", "stadium": "Atlanta", "enabled": false},
  {"id": "m019", "homeTeam": "Estados Unidos", "awayTeam": "Paraguay", "datetime": "2026-06-12T18:00:00Z", "phase": "groups", "group": "D", "stadium": "Los Ãngeles", "enabled": false},
  {"id": "m020", "homeTeam": "Australia", "awayTeam": "TurquÃ­a", "datetime": "2026-06-13T01:00:00Z", "phase": "groups", "group": "D", "stadium": "Vancouver", "enabled": false},
  {"id": "m021", "homeTeam": "TurquÃ­a", "awayTeam": "Paraguay", "datetime": "2026-06-18T19:00:00Z", "phase": "groups", "group": "D", "stadium": "San Francisco", "enabled": false},
  {"id": "m022", "homeTeam": "Estados Unidos", "awayTeam": "Australia", "datetime": "2026-06-19T19:00:00Z", "phase": "groups", "group": "D", "stadium": "Seattle", "enabled": false},
  {"id": "m023", "homeTeam": "TurquÃ­a", "awayTeam": "Estados Unidos", "datetime": "2026-06-26T03:00:00Z", "phase": "groups", "group": "D", "stadium": "Los Ãngeles", "enabled": false},
  {"id": "m024", "homeTeam": "Paraguay", "awayTeam": "Australia", "datetime": "2026-06-26T03:00:00Z", "phase": "groups", "group": "D", "stadium": "San Francisco", "enabled": false},
  {"id": "m025", "homeTeam": "Alemania", "awayTeam": "Curazao", "datetime": "2026-06-14T18:00:00Z", "phase": "groups", "group": "E", "stadium": "Houston", "enabled": false},
  {"id": "m026", "homeTeam": "Costa de Marfil", "awayTeam": "Ecuador", "datetime": "2026-06-15T00:00:00Z", "phase": "groups", "group": "E", "stadium": "Filadelfia", "enabled": false},
  {"id": "m027", "homeTeam": "Alemania", "awayTeam": "Costa de Marfil", "datetime": "2026-06-20T20:00:00Z", "phase": "groups", "group": "E", "stadium": "Toronto", "enabled": false},
  {"id": "m028", "homeTeam": "Ecuador", "awayTeam": "Curazao", "datetime": "2026-06-21T00:00:00Z", "phase": "groups", "group": "E", "stadium": "Kansas City", "enabled": false},
  {"id": "m029", "homeTeam": "Ecuador", "awayTeam": "Alemania", "datetime": "2026-06-25T20:00:00Z", "phase": "groups", "group": "E", "stadium": "Nueva York/NJ", "enabled": false},
  {"id": "m030", "homeTeam": "Curazao", "awayTeam": "Costa de Marfil", "datetime": "2026-06-25T20:00:00Z", "phase": "groups", "group": "E", "stadium": "Filadelfia", "enabled": false},
  {"id": "m031", "homeTeam": "PaÃ­ses Bajos", "awayTeam": "JapÃ³n", "datetime": "2026-06-14T19:00:00Z", "phase": "groups", "group": "F", "stadium": "Dallas", "enabled": false},
  {"id": "m032", "homeTeam": "Suecia", "awayTeam": "TÃºnez", "datetime": "2026-06-15T03:00:00Z", "phase": "groups", "group": "F", "stadium": "Monterrey", "enabled": false},
  {"id": "m033", "homeTeam": "PaÃ­ses Bajos", "awayTeam": "Suecia", "datetime": "2026-06-20T17:00:00Z", "phase": "groups", "group": "F", "stadium": "Houston", "enabled": false},
  {"id": "m034", "homeTeam": "TÃºnez", "awayTeam": "JapÃ³n", "datetime": "2026-06-20T04:00:00Z", "phase": "groups", "group": "F", "stadium": "Monterrey", "enabled": false},
  {"id": "m035", "homeTeam": "JapÃ³n", "awayTeam": "Suecia", "datetime": "2026-06-26T01:00:00Z", "phase": "groups", "group": "F", "stadium": "Dallas", "enabled": false},
  {"id": "m036", "homeTeam": "TÃºnez", "awayTeam": "PaÃ­ses Bajos", "datetime": "2026-06-26T01:00:00Z", "phase": "groups", "group": "F", "stadium": "Kansas City", "enabled": false},
  {"id": "m037", "homeTeam": "IrÃ¡n", "awayTeam": "Nueva Zelandia", "datetime": "2026-06-16T04:00:00Z", "phase": "groups", "group": "G", "stadium": "Los Ãngeles", "enabled": false},
  {"id": "m038", "homeTeam": "BÃ©lgica", "awayTeam": "Egipto", "datetime": "2026-06-15T20:00:00Z", "phase": "groups", "group": "G", "stadium": "Seattle", "enabled": false},
  {"id": "m039", "homeTeam": "BÃ©lgica", "awayTeam": "IrÃ¡n", "datetime": "2026-06-21T20:00:00Z", "phase": "groups", "group": "G", "stadium": "Los Ãngeles", "enabled": false},
  {"id": "m040", "homeTeam": "Nueva Zelandia", "awayTeam": "Egipto", "datetime": "2026-06-22T02:00:00Z", "phase": "groups", "group": "G", "stadium": "Vancouver", "enabled": false},
  {"id": "m041", "homeTeam": "Egipto", "awayTeam": "IrÃ¡n", "datetime": "2026-06-27T02:00:00Z", "phase": "groups", "group": "G", "stadium": "Seattle", "enabled": false},
  {"id": "m042", "homeTeam": "Nueva Zelandia", "awayTeam": "BÃ©lgica", "datetime": "2026-06-27T02:00:00Z", "phase": "groups", "group": "G", "stadium": "Vancouver", "enabled": false},
  {"id": "m043", "homeTeam": "EspaÃ±a", "awayTeam": "Cabo Verde", "datetime": "2026-06-15T18:00:00Z", "phase": "groups", "group": "H", "stadium": "Atlanta", "enabled": false},
  {"id": "m044", "homeTeam": "Arabia Saudita", "awayTeam": "Uruguay", "datetime": "2026-06-16T00:00:00Z", "phase": "groups", "group": "H", "stadium": "Miami", "enabled": false},
  {"id": "m045", "homeTeam": "EspaÃ±a", "awayTeam": "Arabia Saudita", "datetime": "2026-06-21T18:00:00Z", "phase": "groups", "group": "H", "stadium": "Atlanta", "enabled": false},
  {"id": "m046", "homeTeam": "Uruguay", "awayTeam": "Cabo Verde", "datetime": "2026-06-22T00:00:00Z", "phase": "groups", "group": "H", "stadium": "Miami", "enabled": false},
  {"id": "m047", "homeTeam": "Cabo Verde", "awayTeam": "Arabia Saudita", "datetime": "2026-06-26T19:00:00Z", "phase": "groups", "group": "H", "stadium": "Houston", "enabled": false},
  {"id": "m048", "homeTeam": "Uruguay", "awayTeam": "EspaÃ±a", "datetime": "2026-06-27T02:00:00Z", "phase": "groups", "group": "H", "stadium": "Guadalajara", "enabled": false},
  {"id": "m049", "homeTeam": "Francia", "awayTeam": "Senegal", "datetime": "2026-06-16T20:00:00Z", "phase": "groups", "group": "I", "stadium": "Nueva York/NJ", "enabled": false},
  {"id": "m050", "homeTeam": "Iraq", "awayTeam": "Noruega", "datetime": "2026-06-16T22:00:00Z", "phase": "groups", "group": "I", "stadium": "Boston", "enabled": false},
  {"id": "m051", "homeTeam": "Francia", "awayTeam": "Iraq", "datetime": "2026-06-22T22:00:00Z", "phase": "groups", "group": "I", "stadium": "Filadelfia", "enabled": false},
  {"id": "m052", "homeTeam": "Noruega", "awayTeam": "Senegal", "datetime": "2026-06-23T00:00:00Z", "phase": "groups", "group": "I", "stadium": "Nueva York/NJ", "enabled": false},
  {"id": "m053", "homeTeam": "Noruega", "awayTeam": "Francia", "datetime": "2026-06-26T18:00:00Z", "phase": "groups", "group": "I", "stadium": "Boston", "enabled": false},
  {"id": "m054", "homeTeam": "Senegal", "awayTeam": "Iraq", "datetime": "2026-06-26T18:00:00Z", "phase": "groups", "group": "I", "stadium": "Toronto", "enabled": false},
  {"id": "m055", "homeTeam": "Argentina", "awayTeam": "Argelia", "datetime": "2026-06-17T02:00:00Z", "phase": "groups", "group": "J", "stadium": "Kansas City", "enabled": false},
  {"id": "m056", "homeTeam": "Austria", "awayTeam": "Jordania", "datetime": "2026-06-17T04:00:00Z", "phase": "groups", "group": "J", "stadium": "San Francisco", "enabled": false},
  {"id": "m057", "homeTeam": "Argentina", "awayTeam": "Austria", "datetime": "2026-06-22T18:00:00Z", "phase": "groups", "group": "J", "stadium": "Dallas", "enabled": false},
  {"id": "m058", "homeTeam": "Jordania", "awayTeam": "Argelia", "datetime": "2026-06-23T04:00:00Z", "phase": "groups", "group": "J", "stadium": "San Francisco", "enabled": false},
  {"id": "m059", "homeTeam": "Argelia", "awayTeam": "Austria", "datetime": "2026-06-28T02:00:00Z", "phase": "groups", "group": "J", "stadium": "Kansas City", "enabled": false},
  {"id": "m060", "homeTeam": "Jordania", "awayTeam": "Argentina", "datetime": "2026-06-28T02:00:00Z", "phase": "groups", "group": "J", "stadium": "Dallas", "enabled": false},
  {"id": "m061", "homeTeam": "Portugal", "awayTeam": "RD del Congo", "datetime": "2026-06-17T17:00:00Z", "phase": "groups", "group": "K", "stadium": "Houston", "enabled": false},
  {"id": "m062", "homeTeam": "UzbekistÃ¡n", "awayTeam": "Colombia", "datetime": "2026-06-18T02:00:00Z", "phase": "groups", "group": "K", "stadium": "Ciudad de MÃ©xico", "enabled": false},
  {"id": "m063", "homeTeam": "Portugal", "awayTeam": "UzbekistÃ¡n", "datetime": "2026-06-23T17:00:00Z", "phase": "groups", "group": "K", "stadium": "Houston", "enabled": false},
  {"id": "m064", "homeTeam": "RD del Congo", "awayTeam": "Colombia", "datetime": "2026-06-24T02:00:00Z", "phase": "groups", "group": "K", "stadium": "Guadalajara", "enabled": false},
  {"id": "m065", "homeTeam": "Colombia", "awayTeam": "Portugal", "datetime": "2026-06-27T23:30:00Z", "phase": "groups", "group": "K", "stadium": "Miami", "enabled": false},
  {"id": "m066", "homeTeam": "RD del Congo", "awayTeam": "UzbekistÃ¡n", "datetime": "2026-06-27T23:30:00Z", "phase": "groups", "group": "K", "stadium": "Atlanta", "enabled": false},
  {"id": "m067", "homeTeam": "Inglaterra", "awayTeam": "Croacia", "datetime": "2026-06-17T19:00:00Z", "phase": "groups", "group": "L", "stadium": "Dallas", "enabled": false},
  {"id": "m068", "homeTeam": "Ghana", "awayTeam": "PanamÃ¡", "datetime": "2026-06-17T23:00:00Z", "phase": "groups", "group": "L", "stadium": "Toronto", "enabled": false},
  {"id": "m069", "homeTeam": "Inglaterra", "awayTeam": "Ghana", "datetime": "2026-06-23T19:00:00Z", "phase": "groups", "group": "L", "stadium": "Boston", "enabled": false},
  {"id": "m070", "homeTeam": "PanamÃ¡", "awayTeam": "Croacia", "datetime": "2026-06-23T23:00:00Z", "phase": "groups", "group": "L", "stadium": "Toronto", "enabled": false},
  {"id": "m071", "homeTeam": "PanamÃ¡", "awayTeam": "Inglaterra", "datetime": "2026-06-27T21:00:00Z", "phase": "groups", "group": "L", "stadium": "Nueva York/NJ", "enabled": false},
  {"id": "m072", "homeTeam": "Croacia", "awayTeam": "Ghana", "datetime": "2026-06-27T21:00:00Z", "phase": "groups", "group": "L", "stadium": "Filadelfia", "enabled": false},
];

